;;; test_my_ime_elisp.el --- Tests for my-ime.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'org)

(load-file (expand-file-name "../emacs/my-ime.el"
                             (file-name-directory
                              (or load-file-name buffer-file-name))))

(defun my-ime-test--type-short-kana (text)
  (dolist (char (string-to-list text))
    (let ((last-command-event char))
      (insert char)
      (my-ime--short-kana-post-self-insert))))

(ert-deftest my-ime-short-kana-converts-four-lowercase-romaji ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?u))
      (insert "kyou")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "きょう")))))

(ert-deftest my-ime-short-kana-converts-three-lowercase-romaji ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?i))
      (insert "yoi")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "よい")))))

(ert-deftest my-ime-short-kana-finalizes-fa-word-before-hyphen ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4))
      (my-ime-test--type-short-kana "famiri-")
      (should (equal (buffer-string) "ふぁみりー")))))

(ert-deftest my-ime-short-kana-does-not-convert-org-todo-keyword ()
  (with-temp-buffer
    (org-mode)
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?e))
      (insert "* done")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "* done")))))

(ert-deftest my-ime-short-kana-does-not-convert-uppercase-window ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?E))
      (insert "DONE")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "DONE")))))

(ert-deftest my-ime-eager-mode-line-indicator-uses-left-mule-slot ()
  (with-temp-buffer
    (let ((my-ime-mode-line-left-indicator t))
      (setq-local mode-line-mule-info '("ORIG"))
      (my-ime-eager-mode 1)
      (should (local-variable-p 'mode-line-mule-info))
      (should (equal (car mode-line-mule-info) ""))
      (should (equal (cadr mode-line-mule-info)
                     '(:eval (my-ime--mode-line-segment))))
      (should (equal (substring-no-properties (my-ime--mode-line-segment))
                     "[mj] "))
      (my-ime-eager-mode -1)
      (should (local-variable-p 'mode-line-mule-info))
      (should (equal mode-line-mule-info '("ORIG"))))))

(ert-deftest my-ime-live-mode-line-indicator-takes-priority-while-active ()
  (with-temp-buffer
    (let ((my-ime-mode-line-left-indicator t))
      (setq-local mode-line-mule-info '("ORIG"))
      (my-ime-eager-mode 1)
      (my-ime-live-mode 1)
      (should (equal (substring-no-properties (my-ime--mode-line-segment))
                     "[mj-live] "))
      (my-ime-live-mode -1)
      (should (equal (substring-no-properties (my-ime--mode-line-segment))
                     "[mj] "))
      (my-ime-eager-mode -1)
      (should (local-variable-p 'mode-line-mule-info))
      (should (equal mode-line-mule-info '("ORIG"))))))

(ert-deftest my-ime-live2-mode-line-indicator-takes-priority-while-active ()
  (with-temp-buffer
    (let ((my-ime-mode-line-left-indicator t))
      (setq-local mode-line-mule-info '("ORIG"))
      (my-ime-eager-mode 1)
      (my-ime-live2-mode 1)
      (should (equal (substring-no-properties (my-ime--mode-line-segment))
                     "[mj-live2] "))
      (my-ime-live2-mode -1)
      (should (equal (substring-no-properties (my-ime--mode-line-segment))
                     "[mj] "))
      (my-ime-eager-mode -1)
      (should (local-variable-p 'mode-line-mule-info))
      (should (equal mode-line-mule-info '("ORIG"))))))

(ert-deftest my-ime-live-renders-overlay-without-changing-buffer ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-live-preview-endpoint "/convert"))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (text callback _errback &optional _metadata endpoint)
                   (should (equal text "kyou ha"))
                   (should (equal endpoint "/convert"))
                   (funcall callback "今日は"))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (equal (buffer-string) "kyou ha"))
        (should (overlayp my-ime--live-overlay))
        (should (equal (overlay-get my-ime--live-overlay 'display)
                       (propertize "今日は"
                                   'face 'my-ime-live-preview-face)))))))

(ert-deftest my-ime-live2-renders-preedit-then-convert-overlay ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live2-mode t)
          (my-ime-live-min-chars 1)
          callbacks)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (text callback _errback &optional metadata endpoint)
                   (should (equal text "kyou ha"))
                   (push (list endpoint (alist-get 'trigger metadata) callback)
                         callbacks))))
        (setq my-ime--live-sequence 1)
        (should (my-ime--live2-refresh-preedit 1))
        (funcall (nth 2 (assoc "/preedit" callbacks)) "きょうは")
        (should (equal (buffer-string) "kyou ha"))
        (should (equal (overlay-get my-ime--live-overlay 'display)
                       (propertize "きょうは"
                                   'face 'my-ime-live-preview-face)))
        (should (my-ime--live2-refresh-convert 1))
        (funcall (nth 2 (assoc "/convert" callbacks)) "今日は")
        (should (equal (overlay-get my-ime--live-overlay 'display)
                       (propertize "今日は"
                                   'face 'my-ime-live-preview-face)))
        (should (equal (alist-get 'converted my-ime--live-state) "今日は"))
        (should (equal (alist-get 'original my-ime--live-state) "kyou ha"))))))

(ert-deftest my-ime-live2-late-preedit-does-not-overwrite-convert ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live2-mode t)
          (my-ime-live-min-chars 1)
          callbacks)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata endpoint)
                   (push (cons endpoint callback) callbacks))))
        (setq my-ime--live-sequence 1)
        (should (my-ime--live2-refresh-preedit 1))
        (should (my-ime--live2-refresh-convert 1))
        (funcall (cdr (assoc "/convert" callbacks)) "今日は")
        (funcall (cdr (assoc "/preedit" callbacks)) "きょうは")
        (should (equal (overlay-get my-ime--live-overlay 'display)
                       (propertize "今日は"
                                   'face 'my-ime-live-preview-face)))
        (should (equal (alist-get 'endpoint my-ime--live-state) "/convert"))))))

(ert-deftest my-ime-live2-discards-stale-convert-response ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live2-mode t)
          (my-ime-live-min-chars 1)
          callback)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text response-callback _errback
                          &optional _metadata _endpoint)
                   (setq callback response-callback))))
        (setq my-ime--live-sequence 1)
        (should (my-ime--live2-refresh-convert 1))
        (insert "!")
        (setq my-ime--live-sequence 2)
        (funcall callback "今日は")
        (should-not (overlayp my-ime--live-overlay))
        (should-not my-ime--live-state)
        (should (equal (buffer-string) "kyou ha!"))))))

(ert-deftest my-ime-live2-candidate-selection-uses-original-source ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live2-mode t)
          (my-ime-live-min-chars 1)
          captured-source)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "今日は")))
                ((symbol-function 'my-ime--replace-bounds-with-selected-candidate)
                 (lambda (beg end _label _metadata _allow-unsafe)
                   (setq captured-source
                         (buffer-substring-no-properties beg end)))))
        (setq my-ime--live-sequence 1)
        (should (my-ime--live2-refresh-convert 1))
        (my-ime-live-select-candidate)
        (should (equal captured-source "kyou ha"))))))

(ert-deftest my-ime-live-discards-stale-response ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          callback)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text response-callback _errback
                          &optional _metadata _endpoint)
                   (setq callback response-callback))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (insert "!")
        (setq my-ime--live-sequence 2)
        (funcall callback "今日は")
        (should-not (overlayp my-ime--live-overlay))
        (should-not my-ime--live-state)
        (should (equal (buffer-string) "kyou ha!"))))))

(ert-deftest my-ime-live-commit-replaces-overlay-source ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-live-preview-endpoint "/convert")
          (my-ime-history nil))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "今日は"))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (my-ime-live-commit))
        (should (equal (buffer-string) "今日は"))
        (should-not (overlayp my-ime--live-overlay))
        (should (equal (alist-get 'original (car my-ime-history)) "kyou ha"))
        (should (equal (alist-get 'converted (car my-ime-history)) "今日は"))))))

(ert-deftest my-ime-live-commit-uses-visible-preedit-without-reconvert ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-live-preview-endpoint "/preedit")
          (request-called nil))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "きょうは")))
                ((symbol-function 'my-ime--request)
                 (lambda (text _metadata endpoint)
                   (setq request-called (list text endpoint))
                   "should-not-be-used")))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (my-ime-live-commit))
        (should (equal (buffer-string) "きょうは"))
        (should-not request-called)))))

(ert-deftest my-ime-live-commit-does-not-convert-without-live-state ()
  (with-temp-buffer
    (insert "日本語のことを考える")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-history nil)
          (request-called nil))
      (cl-letf (((symbol-function 'my-ime--request)
                 (lambda (text _metadata endpoint)
                   (setq request-called (list text endpoint))
                   "should-not-be-used")))
        (should-not (my-ime-live-commit))
        (should (equal (buffer-string) "日本語のことを考える"))
        (should-not request-called)
        (should-not my-ime-history)))))

(ert-deftest my-ime-live-mode-ret-commits-visible-state ()
  (should (eq (lookup-key my-ime-live-mode-map (kbd "RET"))
              #'my-ime-live-commit-and-newline))
  (should (eq (lookup-key my-ime-live-mode-map (kbd "C-c j RET"))
              #'my-ime-live-commit)))

(ert-deftest my-ime-live-ret-commits-and-newlines-without-reconvert ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (request-called nil))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "今日は")))
                ((symbol-function 'my-ime--request)
                 (lambda (text _metadata endpoint)
                   (setq request-called (list text endpoint))
                   "should-not-be-used")))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (my-ime-live-commit-and-newline)
        (should (equal (buffer-string) "今日は\n"))
        (should-not request-called)
        (should-not (overlayp my-ime--live-overlay))))))

(ert-deftest my-ime-live2-ret-after-candidate-selection-ignores-live-state ()
  (with-temp-buffer
    (insert "imeの事を考える")
    (let ((my-ime-live2-mode t)
          (my-ime-history nil))
      (let ((overlay (make-overlay (point-min) (point-max)))
            (beg-marker (copy-marker (point-min)))
            (end-marker (copy-marker (point-max) t)))
        (overlay-put overlay 'display "い目の事を考得る")
        (setq my-ime--live-overlay overlay
              my-ime--live-state
              `((beg_marker . ,beg-marker)
                (end_marker . ,end-marker)
                (original . "imeの事を考える")
                (converted . "い目の事を考得る")
                (metadata . nil)
                (endpoint . "/convert"))
              my-ime--suppress-next-ret-conversion t)
        (my-ime-live-commit-and-newline)
        (should (equal (buffer-string) "imeの事を考える\n"))
        (should-not my-ime--suppress-next-ret-conversion)
        (should-not (overlayp my-ime--live-overlay))
        (should-not my-ime-history)))))

(ert-deftest my-ime-live2-candidate-selection-ret-keeps-manual-term-choice ()
  (with-temp-buffer
    (insert ";;ime;;nokotowokangaeru")
    (let ((my-ime-live2-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-history nil)
          requested
          request-called)
      (cl-letf (((symbol-function 'my-ime--request-payload)
                 (lambda (text _metadata endpoint)
                   (setq requested (list text endpoint))
                   '((candidates . ("imeの事を考える")))))
                ((symbol-function 'my-ime--request)
                 (lambda (text _metadata endpoint)
                   (setq request-called (list text endpoint))
                   "should-not-be-used")))
        (my-ime-live-select-candidate)
        (should (equal requested '(";;ime;;nokotowokangaeru" "/candidates")))
        (should (equal (buffer-string) "imeの事を考える"))
        (should my-ime--suppress-next-ret-conversion)
        (setq my-ime--live-overlay (make-overlay (point-min) (point-max))
              my-ime--live-state
              `((beg_marker . ,(copy-marker (point-min)))
                (end_marker . ,(copy-marker (point-max) t))
                (original . "imeの事を考える")
                (converted . "い目の事を考得る")
                (metadata . nil)
                (endpoint . "/convert")))
        (my-ime-live-commit-and-newline)
        (should (equal (buffer-string) "imeの事を考える\n"))
        (should-not my-ime--suppress-next-ret-conversion)
        (should-not request-called)
        (should-not my-ime--live-state)))))

(ert-deftest my-ime-live2-candidate-selection-does-not-refresh-selected-text ()
  (with-temp-buffer
    (insert ";;test;;nokotowokangaetemita")
    (let ((my-ime-live2-mode t)
          (my-ime-live-min-chars 1)
          requested
          refresh-requested)
      (add-hook 'after-change-functions #'my-ime--live-after-change nil t)
      (cl-letf (((symbol-function 'my-ime--request-payload)
                 (lambda (text _metadata endpoint)
                   (setq requested (list text endpoint))
                   '((candidates . ("testの事を考えてみた")))))
                ((symbol-function 'my-ime--request-async)
                 (lambda (text _callback _errback &optional _metadata endpoint)
                   (setq refresh-requested (list text endpoint)))))
        (my-ime-live-select-candidate)
        (should (equal requested
                       '(";;test;;nokotowokangaetemita" "/candidates")))
        (should (equal (buffer-string) "testの事を考えてみた"))
        (should-not refresh-requested)
        (should-not (overlayp my-ime--live-overlay))
        (should-not (timerp my-ime--live2-convert-timer))))))

(ert-deftest my-ime-live2-company-candidate-replacement-does-not-refresh ()
  (with-temp-buffer
    (insert ";;test;;nokotowokangaetemita")
    (let ((my-ime-live2-mode t)
          (my-ime-live-min-chars 1)
          (my-ime--company-original ";;test;;nokotowokangaetemita")
          (my-ime--company-candidates '("testの事を考えてみた"))
          refresh-requested)
      (add-hook 'after-change-functions #'my-ime--live-after-change nil t)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (text _callback _errback &optional _metadata endpoint)
                   (setq refresh-requested (list text endpoint)))))
        (delete-region (point-min) (point-max))
        (insert "testの事を考えてみた")
        (should (equal (buffer-string) "testの事を考えてみた"))
        (should-not refresh-requested)
        (should-not (overlayp my-ime--live-overlay))
        (should-not (timerp my-ime--live2-convert-timer))))))

(ert-deftest my-ime-live-ret-does-not-refresh-previous-line-after-commit ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1))
      (add-hook 'after-change-functions #'my-ime--live-after-change nil t)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "今日は"))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (overlayp my-ime--live-overlay))
        (my-ime-live-commit-and-newline)
        (should (equal (buffer-string) "今日は\n"))
        (should-not (overlayp my-ime--live-overlay))
        (should-not (timerp my-ime--live-timer))))))

;;; test_my_ime_elisp.el ends here
