;;; test_my_ime_elisp.el --- Tests for my-ime.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'org)

(load-file (expand-file-name "../emacs/my-ime.el"
                             (file-name-directory
                              (or load-file-name buffer-file-name))))

(defun my-ime-test--type-short-kana (text)
  (dolist (char (string-to-list text))
    (let ((last-command-event char))
      (insert char)
      (my-ime--short-kana-post-self-insert))))

(ert-deftest my-ime-short-kana-converts-four-lowercase-romaji ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?u))
      (insert "kyou")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "きょう")))))

(ert-deftest my-ime-short-kana-converts-three-lowercase-romaji ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?i))
      (insert "yoi")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "よい")))))

(ert-deftest my-ime-short-kana-finalizes-fa-word-before-hyphen ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4))
      (my-ime-test--type-short-kana "famiri-")
      (should (equal (buffer-string) "ふぁみりー")))))

(ert-deftest my-ime-short-kana-does-not-convert-org-todo-keyword ()
  (with-temp-buffer
    (org-mode)
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?e))
      (insert "* done")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "* done")))))

(ert-deftest my-ime-short-kana-does-not-convert-uppercase-window ()
  (with-temp-buffer
    (let ((my-ime-eager-local-kana nil)
          (my-ime-eager-short-kana-chars 4)
          (last-command-event ?E))
      (insert "DONE")
      (my-ime--short-kana-post-self-insert)
      (should (equal (buffer-string) "DONE")))))

(ert-deftest my-ime-live-renders-overlay-without-changing-buffer ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-live-preview-endpoint "/convert"))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (text callback _errback &optional _metadata endpoint)
                   (should (equal text "kyou ha"))
                   (should (equal endpoint "/convert"))
                   (funcall callback "今日は"))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (equal (buffer-string) "kyou ha"))
        (should (overlayp my-ime--live-overlay))
        (should (equal (overlay-get my-ime--live-overlay 'display)
                       (propertize "今日は"
                                   'face 'my-ime-live-preview-face)))))))

(ert-deftest my-ime-live-discards-stale-response ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          callback)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text response-callback _errback
                          &optional _metadata _endpoint)
                   (setq callback response-callback))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (insert "!")
        (setq my-ime--live-sequence 2)
        (funcall callback "今日は")
        (should-not (overlayp my-ime--live-overlay))
        (should-not my-ime--live-state)
        (should (equal (buffer-string) "kyou ha!"))))))

(ert-deftest my-ime-live-commit-replaces-overlay-source ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-live-preview-endpoint "/convert")
          (my-ime-history nil))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "今日は"))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (my-ime-live-commit))
        (should (equal (buffer-string) "今日は"))
        (should-not (overlayp my-ime--live-overlay))
        (should (equal (alist-get 'original (car my-ime-history)) "kyou ha"))
        (should (equal (alist-get 'converted (car my-ime-history)) "今日は"))))))

(ert-deftest my-ime-live-commit-uses-visible-preedit-without-reconvert ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-live-preview-endpoint "/preedit")
          (request-called nil))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "きょうは")))
                ((symbol-function 'my-ime--request)
                 (lambda (text _metadata endpoint)
                   (setq request-called (list text endpoint))
                   "should-not-be-used")))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (my-ime-live-commit))
        (should (equal (buffer-string) "きょうは"))
        (should-not request-called)))))

(ert-deftest my-ime-live-commit-does-not-convert-without-live-state ()
  (with-temp-buffer
    (insert "日本語のことを考える")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (my-ime-history nil)
          (request-called nil))
      (cl-letf (((symbol-function 'my-ime--request)
                 (lambda (text _metadata endpoint)
                   (setq request-called (list text endpoint))
                   "should-not-be-used")))
        (should-not (my-ime-live-commit))
        (should (equal (buffer-string) "日本語のことを考える"))
        (should-not request-called)
        (should-not my-ime-history)))))

(ert-deftest my-ime-live-mode-ret-commits-visible-state ()
  (should (eq (lookup-key my-ime-live-mode-map (kbd "RET"))
              #'my-ime-live-commit-and-newline))
  (should (eq (lookup-key my-ime-live-mode-map (kbd "C-c j RET"))
              #'my-ime-live-commit)))

(ert-deftest my-ime-live-ret-commits-and-newlines-without-reconvert ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1)
          (request-called nil))
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "今日は")))
                ((symbol-function 'my-ime--request)
                 (lambda (text _metadata endpoint)
                   (setq request-called (list text endpoint))
                   "should-not-be-used")))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (my-ime-live-commit-and-newline)
        (should (equal (buffer-string) "今日は\n"))
        (should-not request-called)
        (should-not (overlayp my-ime--live-overlay))))))

(ert-deftest my-ime-live-ret-does-not-refresh-previous-line-after-commit ()
  (with-temp-buffer
    (insert "kyou ha")
    (let ((my-ime-live-mode t)
          (my-ime-live-min-chars 1))
      (add-hook 'after-change-functions #'my-ime--live-after-change nil t)
      (cl-letf (((symbol-function 'my-ime--request-async)
                 (lambda (_text callback _errback &optional _metadata _endpoint)
                   (funcall callback "今日は"))))
        (setq my-ime--live-sequence 1)
        (my-ime--live-refresh 1)
        (should (overlayp my-ime--live-overlay))
        (my-ime-live-commit-and-newline)
        (should (equal (buffer-string) "今日は\n"))
        (should-not (overlayp my-ime--live-overlay))
        (should-not (timerp my-ime--live-timer))))))

;;; test_my_ime_elisp.el ends here
